replicaCount: 1

image:
  repository: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/hello-world-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80        # external port
  targetPort: 5000  # Flask port in container

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
